export const initialData = {
  firstName: "",
  lastName: "",
  birthDate: "",
  phone: "",
  address: "",
  zip: "",
  city: "",
  state: "",
  companyName: "",
  companyCreationDate: "",
  companyAddress: "",
  companyCity: "",
  companyState: "",
  companyZip: "",
  companyPhone: "",
  email: "",
  password: "",
  confirmPassword: "",
  encryptFormData: [],
};

export const inputs = [
  {
    id: 1,
    name: "firstName",
    label: "First Name",
    type: "text",
    placeholder: "First Name",
    required: true,
  },
  {
    id: 2,
    name: "lastName",
    label: "Last Name",
    type: "text",
    placeholder: "Last Name",
    required: true,
  },
  {
    id: 3,
    name: "birthDate",
    label: "Birth",
    type: "text",
    placeholder: "Birth",
    required: true,
  },
  {
    id: 4,
    name: "phone",
    label: "Phone",
    type: "text",
    placeholder: "Phone",
    required: true,
  },
  {
    id: 5,
    name: "address",
    label: "Address",
    type: "text",
    placeholder: "Address",
    required: true,
  },
  {
    id: 6,
    name: "zip",
    label: "Zip",
    type: "text",
    placeholder: "Zip",
    required: true,
  },
  {
    id: 7,
    name: "city",
    label: "City",
    type: "text",
    placeholder: "City",
    required: true,
  },
  {
    id: 8,
    name: "state",
    label: "State",
    type: "text",
    placeholder: "State",
    required: true,
  },
  {
    id: 9,
    name: "companyName",
    label: "Company Name",
    type: "text",
    placeholder: "Company Name",
    required: true,
  },
  {
    id: 10,
    name: "companyCreationDate",
    label: "Company Creation Date",
    type: "text",
    placeholder: "Company Creation Date",
    required: true,
  },
  {
    id: 11,
    name: "companyAddress",
    label: "Company Address",
    type: "text",
    placeholder: "Company Address",
    required: true,
  },
  {
    id: 12,
    name: "companyCity",
    label: "Company City",
    type: "text",
    placeholder: "Company City",
    required: true,
  },
  {
    id: 13,
    name: "companyState",
    label: "Company State",
    type: "text",
    placeholder: "Company State",
    required: true,
  },
  {
    id: 14,
    name: "companyZip",
    label: "Company Zip",
    type: "text",
    placeholder: "Company Zip",
    required: true,
  },
  {
    id: 15,
    name: "companyPhone",
    label: "Company Phone",
    type: "text",
    placeholder: "Company Phone",
    required: true,
  },
  {
    id: 16,
    name: "email",
    label: "Email",
    type: "text",
    placeholder: "Email",
    required: true,
  },
  {
    id: 17,
    name: "password",
    label: "Password",
    type: "password",
    placeholder: "Password",
    required: true,
  },
  {
    id: 18,
    name: "confirmPassword",
    label: "Confirm Password",
    type: "password",
    placeholder: "Confirm Password",
    required: true,
  },
  {
    id: 19,
    name: "files",
    label: "Files",
    type: "file",
    placeholder: "Files",
  },
];
